<?php

namespace Database\Seeders;

use App\Models\Bairro;
use Illuminate\Database\Seeder;

class BairroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    
        Bairro::insert(['id'=>'1','bairro'=>'--']);
        Bairro::insert(['id'=>'878','bairro'=>'Bom Retiro']);
        Bairro::insert(['id'=>'879','bairro'=>'Itaum']);
        Bairro::insert(['id'=>'880','bairro'=>'Fatima']);
        Bairro::insert(['id'=>'881','bairro'=>'Floresta']);
        Bairro::insert(['id'=>'882','bairro'=>'Guanabara']);
        Bairro::insert(['id'=>'883','bairro'=>'Comasa']);
        Bairro::insert(['id'=>'884','bairro'=>'Iririu']);
        Bairro::insert(['id'=>'885','bairro'=>'Morro do Meio']);
        Bairro::insert(['id'=>'886','bairro'=>'Nova Brasilia']);
        Bairro::insert(['id'=>'887','bairro'=>'Bucarein']);
        Bairro::insert(['id'=>'888','bairro'=>'João Costa']);
        Bairro::insert(['id'=>'889','bairro'=>'Costa e Silva']);
        Bairro::insert(['id'=>'890','bairro'=>'Pirabeiraba']);
        Bairro::insert(['id'=>'891','bairro'=>'Glória']);
        Bairro::insert(['id'=>'892','bairro'=>'Vilaa Nova']);
        Bairro::insert(['id'=>'893','bairro'=>'Petropolis']);
        Bairro::insert(['id'=>'894','bairro'=>'Boehmerwald']);
        Bairro::insert(['id'=>'895','bairro'=>'Boa Vista']);
        Bairro::insert(['id'=>'896','bairro'=>'Paranáguamirim']);
        Bairro::insert(['id'=>'897','bairro'=>'Jardim Iririu']);
        Bairro::insert(['id'=>'898','bairro'=>'Anita Garibaldi']);
        Bairro::insert(['id'=>'899','bairro'=>'Jarivatuba']);
        Bairro::insert(['id'=>'900','bairro'=>'São Marcos']);
        Bairro::insert(['id'=>'901','bairro'=>'Itinga']);
        Bairro::insert(['id'=>'902','bairro'=>'Espinheiros']);
        Bairro::insert(['id'=>'903','bairro'=>'Rio Bonito']);
        Bairro::insert(['id'=>'904','bairro'=>'Vilaa Cubatao']);
        Bairro::insert(['id'=>'905','bairro'=>'Morro do Amaral']);
        Bairro::insert(['id'=>'906','bairro'=>'Centro Pirabeiraba']);
        Bairro::insert(['id'=>'907','bairro'=>'Rio Bonito Piraberaba']);
        Bairro::insert(['id'=>'908','bairro'=>'Santa Catarina']);
        Bairro::insert(['id'=>'909','bairro'=>'Saguacu']);
        Bairro::insert(['id'=>'910','bairro'=>'America']);
        Bairro::insert(['id'=>'911','bairro'=>'Ademar Garcia']);
        Bairro::insert(['id'=>'912','bairro'=>'Aventureiro']);
        Bairro::insert(['id'=>'913','bairro'=>'Centro']);
        Bairro::insert(['id'=>'914','bairro'=>'Zona Industrial']);
        Bairro::insert(['id'=>'915','bairro'=>'Sto Antônio']);
        Bairro::insert(['id'=>'916','bairro'=>'Profipo']);
        Bairro::insert(['id'=>'917','bairro'=>'Dona Francisca Piraberaba']);
        Bairro::insert(['id'=>'918','bairro'=>'Jardim Paraiso']);
        Bairro::insert(['id'=>'919','bairro'=>'Jardim Sofia']);
        Bairro::insert(['id'=>'920','bairro'=>'Adhemar Garcia']);
        Bairro::insert(['id'=>'921','bairro'=>'Atiradores']);
        Bairro::insert(['id'=>'922','bairro'=>'Parque Guarani']);
        Bairro::insert(['id'=>'923','bairro'=>'Ulysses Guimaraes']);
        Bairro::insert(['id'=>'924','bairro'=>'Zona Industrial Norte']);
        Bairro::insert(['id'=>'925','bairro'=>'Jardim Paraiso 4']);
        Bairro::insert(['id'=>'926','bairro'=>'Santo Antônio']);
        Bairro::insert(['id'=>'927','bairro'=>'Bohemerwaldt']);
        Bairro::insert(['id'=>'928','bairro'=>'Canela']);
        Bairro::insert(['id'=>'929','bairro'=>'Ulisses Guimaraes']);
        Bairro::insert(['id'=>'930','bairro'=>'Comasa Boa Vista']);
        Bairro::insert(['id'=>'931','bairro'=>'Escolinha']);
        Bairro::insert(['id'=>'932','bairro'=>'Jariuatuba']);
        Bairro::insert(['id'=>'933','bairro'=>'Boehmerwaldt']);
        Bairro::insert(['id'=>'934','bairro'=>'Centro de Florianópolis']);
        Bairro::insert(['id'=>'935','bairro'=>'Bairro de Cacupé']);
        Bairro::insert(['id'=>'936','bairro'=>'São João do Rio Vermelho']);
        Bairro::insert(['id'=>'937','bairro'=>'Bairro Barra da Lagoa']);
        Bairro::insert(['id'=>'938','bairro'=>'Pântano do Sul']);
        Bairro::insert(['id'=>'939','bairro'=>'Armação do Pântano do Sul']);
        Bairro::insert(['id'=>'940','bairro'=>'Estreito']);
        Bairro::insert(['id'=>'941','bairro'=>'Trindade']);
        Bairro::insert(['id'=>'942','bairro'=>'Carianos']);
        Bairro::insert(['id'=>'943','bairro'=>'Balneário']);
        Bairro::insert(['id'=>'944','bairro'=>'Bom Abrigo']);
        Bairro::insert(['id'=>'945','bairro'=>'Capoeiras']);
        Bairro::insert(['id'=>'946','bairro'=>'Coqueiros']);
        Bairro::insert(['id'=>'947','bairro'=>'Itaguaçu']);
        Bairro::insert(['id'=>'948','bairro'=>'Jardim Atlântico']);
        Bairro::insert(['id'=>'949','bairro'=>'Agronômica']);
        Bairro::insert(['id'=>'950','bairro'=>'Córrego Grande']);
        Bairro::insert(['id'=>'951','bairro'=>'José Mendes']);
        Bairro::insert(['id'=>'952','bairro'=>'João Paulo']);
        Bairro::insert(['id'=>'953','bairro'=>'Itacorubi']);
        Bairro::insert(['id'=>'954','bairro'=>'Monte Verde']);
        Bairro::insert(['id'=>'955','bairro'=>'Bairro Pantanal']);
        Bairro::insert(['id'=>'956','bairro'=>'Saco dos Limões']);
        Bairro::insert(['id'=>'957','bairro'=>'Santa Mônica']);
        Bairro::insert(['id'=>'958','bairro'=>'Bairro Cachoeira do Bom Jesus']);
        Bairro::insert(['id'=>'959','bairro'=>'Canasvieiras']);
        Bairro::insert(['id'=>'960','bairro'=>'Bairro Daniela']);
        Bairro::insert(['id'=>'961','bairro'=>'Ingleses do Rio Vermelho']);
        Bairro::insert(['id'=>'962','bairro'=>'Jurerê Tradicional']);
        Bairro::insert(['id'=>'963','bairro'=>'Bairro Jurerê Internacional']);
        Bairro::insert(['id'=>'964','bairro'=>'Bairro Praia Brava']);
        Bairro::insert(['id'=>'965','bairro'=>'Bairro Ponta das Canas']);
        Bairro::insert(['id'=>'966','bairro'=>'Santo Antônio de Lisboa']);
        Bairro::insert(['id'=>'967','bairro'=>'Bairro Sambaqui']);
        Bairro::insert(['id'=>'968','bairro'=>'Bairro Lagoa da Conceição']);
        Bairro::insert(['id'=>'969','bairro'=>'Bairro Campeche']);
        Bairro::insert(['id'=>'970','bairro'=>'Costeira do Pirajubaé']);
        Bairro::insert(['id'=>'971','bairro'=>'Ribeirão da Ilha']);
        Bairro::insert(['id'=>'972','bairro'=>'Rio Tavares']);
        Bairro::insert(['id'=>'973','bairro'=>'Saco Grande']);
        Bairro::insert(['id'=>'974','bairro'=>'Bairro da Tapera']);
        Bairro::insert(['id'=>'975','bairro'=>'Carvoeira']);
        Bairro::insert(['id'=>'976','bairro'=>'Água Verde']);
        Bairro::insert(['id'=>'977','bairro'=>'Badenfurt']);
        Bairro::insert(['id'=>'978','bairro'=>'Boa Vista']);
        Bairro::insert(['id'=>'979','bairro'=>'Bom Retiro']);
        Bairro::insert(['id'=>'980','bairro'=>'Centro']);
        Bairro::insert(['id'=>'981','bairro'=>'Escola Agrícola']);
        Bairro::insert(['id'=>'982','bairro'=>'Fidélis']);
        Bairro::insert(['id'=>'983','bairro'=>'Fortaleza']);
        Bairro::insert(['id'=>'984','bairro'=>'Fortaleza Alta']);
        Bairro::insert(['id'=>'985','bairro'=>'Garcia']);
        Bairro::insert(['id'=>'986','bairro'=>'Glória']);
        Bairro::insert(['id'=>'987','bairro'=>'Itoupava Central']);
        Bairro::insert(['id'=>'988','bairro'=>'Itoupava Norte']);
        Bairro::insert(['id'=>'989','bairro'=>'Itoupava Seca']);
        Bairro::insert(['id'=>'990','bairro'=>'Itoupavazinha']);
        Bairro::insert(['id'=>'991','bairro'=>'Jardim Blumenau']);
        Bairro::insert(['id'=>'992','bairro'=>'Nova Esperança']);
        Bairro::insert(['id'=>'993','bairro'=>'Passo Manso']);
        Bairro::insert(['id'=>'994','bairro'=>'Ponta Aguda']);
        Bairro::insert(['id'=>'995','bairro'=>'Progresso']);
        Bairro::insert(['id'=>'996','bairro'=>'Ribeirão Fresco']);
        Bairro::insert(['id'=>'997','bairro'=>'Salto']);
        Bairro::insert(['id'=>'998','bairro'=>'Salto do Norte']);
        Bairro::insert(['id'=>'999','bairro'=>'Salto Weissbach']);
        Bairro::insert(['id'=>'1000','bairro'=>'Testo Salto']);
        Bairro::insert(['id'=>'1001','bairro'=>'Tribess']);
        Bairro::insert(['id'=>'1002','bairro'=>'Valparaíso']);
        Bairro::insert(['id'=>'1003','bairro'=>'Velha']);
        Bairro::insert(['id'=>'1004','bairro'=>'Velha Central']);
        Bairro::insert(['id'=>'1005','bairro'=>'Velha Grande']);
        Bairro::insert(['id'=>'1006','bairro'=>'Victor Konder']);
        Bairro::insert(['id'=>'1007','bairro'=>'Vila Formosa']);
        Bairro::insert(['id'=>'1008','bairro'=>'Vila Itoupava']);
        Bairro::insert(['id'=>'1009','bairro'=>'Vila Nova']);
        Bairro::insert(['id'=>'1010','bairro'=>'Vorstadt']);
        Bairro::insert(['id'=>'1011','bairro'=>'Centro']);
        Bairro::insert(['id'=>'1012','bairro'=>'Ponta de Baixo']);
        Bairro::insert(['id'=>'1013','bairro'=>'Fazenda Santo Antônio']);
        Bairro::insert(['id'=>'1014','bairro'=>'Distrito Industrial']);
        Bairro::insert(['id'=>'1015','bairro'=>'Picadas do Sul']);
        Bairro::insert(['id'=>'1016','bairro'=>'Flor de Nápolis']);
        Bairro::insert(['id'=>'1017','bairro'=>'Forquilhinha']);
        Bairro::insert(['id'=>'1018','bairro'=>'Praia Comprida']);
        Bairro::insert(['id'=>'1019','bairro'=>'São Luiz']);
        Bairro::insert(['id'=>'1020','bairro'=>'Roçado']);
        Bairro::insert(['id'=>'1021','bairro'=>'Bosque das Mansões']);
        Bairro::insert(['id'=>'1022','bairro'=>'Potecas']);
        Bairro::insert(['id'=>'1023','bairro'=>'Forquilhas']);
        Bairro::insert(['id'=>'1024','bairro'=>'Sertão do Maruim']);
        Bairro::insert(['id'=>'1025','bairro'=>'Colônia Santana']);
        Bairro::insert(['id'=>'1026','bairro'=>'Barreiros']);
        Bairro::insert(['id'=>'1027','bairro'=>'Nossa Senhora do Rosário']);
        Bairro::insert(['id'=>'1028','bairro'=>'Bela Vista']);
        Bairro::insert(['id'=>'1029','bairro'=>'Jardim Cidade de Florianópolis']);
        Bairro::insert(['id'=>'1030','bairro'=>'Ipiranga']);
        Bairro::insert(['id'=>'1031','bairro'=>'Pedregal']);
        Bairro::insert(['id'=>'1032','bairro'=>'Jardim Santiago']);
        Bairro::insert(['id'=>'1033','bairro'=>'Areias']);
        Bairro::insert(['id'=>'1034','bairro'=>'Serraria']);
        Bairro::insert(['id'=>'1035','bairro'=>'Real Parque']);
        Bairro::insert(['id'=>'1036','bairro'=>'Campinas']);
        Bairro::insert(['id'=>'1037','bairro'=>'Kobrasol']);
        Bairro::insert(['id'=>'1038','bairro'=>'Procasa']);
        Bairro::insert(['id'=>'1039','bairro'=>'Água Santa ']);
        Bairro::insert(['id'=>'1040','bairro'=>'Alvorada ']);
        Bairro::insert(['id'=>'1041','bairro'=>'Araras ']);
        Bairro::insert(['id'=>'1042','bairro'=>'Autódromo ']);
        Bairro::insert(['id'=>'1043','bairro'=>'Bela Vista ']);
        Bairro::insert(['id'=>'1044','bairro'=>'Belvedere ']);
        Bairro::insert(['id'=>'1045','bairro'=>'Boa Vista ']);
        Bairro::insert(['id'=>'1046','bairro'=>'Bom Pastor ']);
        Bairro::insert(['id'=>'1047','bairro'=>'Bom Retiro ']);
        Bairro::insert(['id'=>'1048','bairro'=>'Campestre ']);
        Bairro::insert(['id'=>'1049','bairro'=>'Centro ']);
        Bairro::insert(['id'=>'1050','bairro'=>'Cristo Rei ']);
        Bairro::insert(['id'=>'1051','bairro'=>'Desbravador ']);
        Bairro::insert(['id'=>'1052','bairro'=>'Dom Gerônimo ']);
        Bairro::insert(['id'=>'1053','bairro'=>'Dom Pascoal ']);
        Bairro::insert(['id'=>'1054','bairro'=>'Efapi ']);
        Bairro::insert(['id'=>'1055','bairro'=>'Eldorado ']);
        Bairro::insert(['id'=>'1056','bairro'=>'Engenho Braun ']);
        Bairro::insert(['id'=>'1057','bairro'=>'Esplanada ']);
        Bairro::insert(['id'=>'1058','bairro'=>'Fronteira Sul ']);
        Bairro::insert(['id'=>'1059','bairro'=>'Industrial ']);
        Bairro::insert(['id'=>'1060','bairro'=>'Jardim América ']);
        Bairro::insert(['id'=>'1061','bairro'=>'Jardim Europa ']);
        Bairro::insert(['id'=>'1062','bairro'=>'Jardim Itália ']);
        Bairro::insert(['id'=>'1063','bairro'=>'Jardins ']);
        Bairro::insert(['id'=>'1064','bairro'=>'Lajeado ']);
        Bairro::insert(['id'=>'1065','bairro'=>'Líder ']);
        Bairro::insert(['id'=>'1066','bairro'=>'Maria Goretti ']);
        Bairro::insert(['id'=>'1067','bairro'=>'Monte Belo ']);
        Bairro::insert(['id'=>'1068','bairro'=>'Palmital ']);
        Bairro::insert(['id'=>'1069','bairro'=>'Paraíso ']);
        Bairro::insert(['id'=>'1070','bairro'=>'Parque das Palmeiras ']);
        Bairro::insert(['id'=>'1071','bairro'=>'Passo dos Fortes ']);
        Bairro::insert(['id'=>'1072','bairro'=>'Pinheirinho ']);
        Bairro::insert(['id'=>'1073','bairro'=>'Presidente Médici ']);
        Bairro::insert(['id'=>'1074','bairro'=>'Progresso ']);
        Bairro::insert(['id'=>'1075','bairro'=>'Quedas do Palmital ']);
        Bairro::insert(['id'=>'1076','bairro'=>'SAIC ']);
        Bairro::insert(['id'=>'1077','bairro'=>'Santa Paulina ']);
        Bairro::insert(['id'=>'1078','bairro'=>'Santo Antônio ']);
        Bairro::insert(['id'=>'1079','bairro'=>'Santos Dummond ']);
        Bairro::insert(['id'=>'1080','bairro'=>'São Cristóvão ']);
        Bairro::insert(['id'=>'1081','bairro'=>'São Lucas ']);
        Bairro::insert(['id'=>'1082','bairro'=>'São Pedro ']);
        Bairro::insert(['id'=>'1083','bairro'=>'Seminário ']);
        Bairro::insert(['id'=>'1084','bairro'=>'Trevo ']);
        Bairro::insert(['id'=>'1085','bairro'=>'Universitário ']);
        Bairro::insert(['id'=>'1086','bairro'=>'Vila Real ']);
        Bairro::insert(['id'=>'1087','bairro'=>'Vila Rica ']);
        Bairro::insert(['id'=>'1088','bairro'=>'Arraial dos Cunhãs']);
        Bairro::insert(['id'=>'1089','bairro'=>'Baía']);
        Bairro::insert(['id'=>'1090','bairro'=>'Balneário Santa Clara']);
        Bairro::insert(['id'=>'1091','bairro'=>'Barra do Rio']);
        Bairro::insert(['id'=>'1092','bairro'=>'Barra Rio']);
        Bairro::insert(['id'=>'1093','bairro'=>'Brilhante I']);
        Bairro::insert(['id'=>'1094','bairro'=>'Brilhante Ii']);
        Bairro::insert(['id'=>'1095','bairro'=>'Cabecudas']);
        Bairro::insert(['id'=>'1096','bairro'=>'Campeche']);
        Bairro::insert(['id'=>'1097','bairro'=>'Canhanduba']);
        Bairro::insert(['id'=>'1098','bairro'=>'Centro']);
        Bairro::insert(['id'=>'1099','bairro'=>'Cidade Nova']);
        Bairro::insert(['id'=>'1100','bairro'=>'Cordeiros']);
        Bairro::insert(['id'=>'1101','bairro'=>'Dom Bosco']);
        Bairro::insert(['id'=>'1102','bairro'=>'Espinheiros']);
        Bairro::insert(['id'=>'1103','bairro'=>'Fazenda']);
        Bairro::insert(['id'=>'1104','bairro'=>'Fazendinha']);
        Bairro::insert(['id'=>'1105','bairro'=>'Itaipava']);
        Bairro::insert(['id'=>'1106','bairro'=>'Limoeiro']);
        Bairro::insert(['id'=>'1107','bairro'=>'Murta']);
        Bairro::insert(['id'=>'1108','bairro'=>'Paciência']);
        Bairro::insert(['id'=>'1109','bairro'=>'Praia Brava']);
        Bairro::insert(['id'=>'1110','bairro'=>'Quilometro 12']);
        Bairro::insert(['id'=>'1111','bairro'=>'Ressacada']);
        Bairro::insert(['id'=>'1112','bairro'=>'Salseiros']);
        Bairro::insert(['id'=>'1113','bairro'=>'São João']);
        Bairro::insert(['id'=>'1114','bairro'=>'São Judas']);
        Bairro::insert(['id'=>'1115','bairro'=>'São Roque']);
        Bairro::insert(['id'=>'1116','bairro'=>'São Vicente']);
        Bairro::insert(['id'=>'1117','bairro'=>'Vila Operária']);
        Bairro::insert(['id'=>'1118','bairro'=>'Ana Maria ']);
        Bairro::insert(['id'=>'1119','bairro'=>'Arquimedes Naspolini']);
        Bairro::insert(['id'=>'1120','bairro'=>'Bairro Santa Catarina ']);
        Bairro::insert(['id'=>'1121','bairro'=>'Bosque do Repouso']);
        Bairro::insert(['id'=>'1122','bairro'=>'Brasília ']);
        Bairro::insert(['id'=>'1123','bairro'=>'Centro ']);
        Bairro::insert(['id'=>'1124','bairro'=>'Comerciário ']);
        Bairro::insert(['id'=>'1125','bairro'=>'Cristo Redentor ']);
        Bairro::insert(['id'=>'1126','bairro'=>'Cruzeiro do Sul ']);
        Bairro::insert(['id'=>'1127','bairro'=>'Jardim Angélica ']);
        Bairro::insert(['id'=>'1128','bairro'=>'Jardim das Paineiras ']);
        Bairro::insert(['id'=>'1129','bairro'=>'Maria Céu']);
        Bairro::insert(['id'=>'1130','bairro'=>'Michel ']);
        Bairro::insert(['id'=>'1131','bairro'=>'Mina Brasil']);
        Bairro::insert(['id'=>'1132','bairro'=>'Mina do Mato']);
        Bairro::insert(['id'=>'1133','bairro'=>'Mina do Toco']);
        Bairro::insert(['id'=>'1134','bairro'=>'Mina União']);
        Bairro::insert(['id'=>'1135','bairro'=>'Morro Estevão']);
        Bairro::insert(['id'=>'1136','bairro'=>'Operária Nova']);
        Bairro::insert(['id'=>'1137','bairro'=>'Paraíso ']);
        Bairro::insert(['id'=>'1138','bairro'=>'Pinheirinho ']);
        Bairro::insert(['id'=>'1139','bairro'=>'Pio Corrêa']);
        Bairro::insert(['id'=>'1140','bairro'=>'Próspera ']);
        Bairro::insert(['id'=>'1141','bairro'=>'Renascer ']);
        Bairro::insert(['id'=>'1142','bairro'=>'Santa Bárbara ']);
        Bairro::insert(['id'=>'1143','bairro'=>'São Cristóvão ']);
        Bairro::insert(['id'=>'1144','bairro'=>'Vera Cruz ']);
        Bairro::insert(['id'=>'1145','bairro'=>'Água Verde']);
        Bairro::insert(['id'=>'1146','bairro'=>'Águas Claras']);
        Bairro::insert(['id'=>'1147','bairro'=>'Amizade']);
        Bairro::insert(['id'=>'1148','bairro'=>'Barra do Rio Cerro ']);
        Bairro::insert(['id'=>'1149','bairro'=>'Barra do Rio Molha']);
        Bairro::insert(['id'=>'1150','bairro'=>'Boa Vista']);
        Bairro::insert(['id'=>'1151','bairro'=>'Braço do Ribeirão Cavalo']);
        Bairro::insert(['id'=>'1152','bairro'=>'Centenário']);
        Bairro::insert(['id'=>'1153','bairro'=>'Centro']);
        Bairro::insert(['id'=>'1154','bairro'=>'Chico de Paulo ']);
        Bairro::insert(['id'=>'1155','bairro'=>'Czerniewicz']);
        Bairro::insert(['id'=>'1156','bairro'=>'Estrada Nova']);
        Bairro::insert(['id'=>'1157','bairro'=>'Ilha da Figueira']);
        Bairro::insert(['id'=>'1158','bairro'=>'Jaraguá 84']);
        Bairro::insert(['id'=>'1159','bairro'=>'Jaraguá 99']);
        Bairro::insert(['id'=>'1160','bairro'=>'Jaraguá Esquerdo']);
        Bairro::insert(['id'=>'1161','bairro'=>'João Pessoa']);
        Bairro::insert(['id'=>'1162','bairro'=>'Nereu Ramos']);
        Bairro::insert(['id'=>'1163','bairro'=>'Nova Brasília']);
        Bairro::insert(['id'=>'1164','bairro'=>'Parque Malwee']);
        Bairro::insert(['id'=>'1165','bairro'=>'Rau ']);
        Bairro::insert(['id'=>'1166','bairro'=>'Ribeirão Cavalo']);
        Bairro::insert(['id'=>'1167','bairro'=>'Rio Cerro I ']);
        Bairro::insert(['id'=>'1168','bairro'=>'Rio Cerro II ']);
        Bairro::insert(['id'=>'1169','bairro'=>'Rio da Luz']);
        Bairro::insert(['id'=>'1170','bairro'=>'Rio Molha']);
        Bairro::insert(['id'=>'1171','bairro'=>'Santa Luzia']);
        Bairro::insert(['id'=>'1172','bairro'=>'Santo Antônio']);
        Bairro::insert(['id'=>'1173','bairro'=>'São Luís ']);
        Bairro::insert(['id'=>'1174','bairro'=>'Tifa Martins ']);
        Bairro::insert(['id'=>'1175','bairro'=>'Tifa Monos']);
        Bairro::insert(['id'=>'1176','bairro'=>'Três Rios do Norte']);
        Bairro::insert(['id'=>'1177','bairro'=>'Três Rios do Sul']);
        Bairro::insert(['id'=>'1178','bairro'=>'Vieira ']);
        Bairro::insert(['id'=>'1179','bairro'=>'Vila Baependi']);
        Bairro::insert(['id'=>'1180','bairro'=>'Vila Lalau']);
        Bairro::insert(['id'=>'1181','bairro'=>'Vila Lenzi']);
        Bairro::insert(['id'=>'1182','bairro'=>'Vila Nova']);
        Bairro::insert(['id'=>'1183','bairro'=>'Bela Vista']);
        Bairro::insert(['id'=>'1184','bairro'=>'Aririu']);
        Bairro::insert(['id'=>'1185','bairro'=>'Pedra Branca']);
        Bairro::insert(['id'=>'1186','bairro'=>'São Sebastião']);
        Bairro::insert(['id'=>'1187','bairro'=>'Barra do Aririú']);
        Bairro::insert(['id'=>'1188','bairro'=>'Centro']);
        Bairro::insert(['id'=>'1189','bairro'=>'Ponte do Imaruim']);
        Bairro::insert(['id'=>'1190','bairro'=>'Praia de Fora']);
        Bairro::insert(['id'=>'1191','bairro'=>'Nova Palhoça']);
        Bairro::insert(['id'=>'1192','bairro'=>'Pachecos']);
        Bairro::insert(['id'=>'1193','bairro'=>'Jardim Eldorado']);
        Bairro::insert(['id'=>'1194','bairro'=>'Passa Vinte']);
        Bairro::insert(['id'=>'1195','bairro'=>'Guarda do Cubatão']);
        Bairro::insert(['id'=>'1196','bairro'=>'Madri']);
        Bairro::insert(['id'=>'1197','bairro'=>'Caminho Novo']);
        Bairro::insert(['id'=>'1198','bairro'=>'Rio Grande']);
        Bairro::insert(['id'=>'1199','bairro'=>'Aririú da Formiga']);
        Bairro::insert(['id'=>'1200','bairro'=>'Pagani']);
        Bairro::insert(['id'=>'1201','bairro'=>'Alto Aririu']);
        Bairro::insert(['id'=>'1202','bairro'=>'Cidade Universitária Pedra Branca']);
        Bairro::insert(['id'=>'1203','bairro'=>'Jardim Coqueiros']);
        Bairro::insert(['id'=>'1204','bairro'=>'Jardim Aquarius']);
        Bairro::insert(['id'=>'1205','bairro'=>'Guarda do Embaú ']);
        Bairro::insert(['id'=>'1206','bairro'=>'Jardim das Palmeiras']);
        Bairro::insert(['id'=>'1207','bairro'=>'Pinheira ']);
        Bairro::insert(['id'=>'1208','bairro'=>'Enseada do Brito ']);
        Bairro::insert(['id'=>'1209','bairro'=>'Brejarú']);
        Bairro::insert(['id'=>'1210','bairro'=>'Praia do Meio ']);
        Bairro::insert(['id'=>'1211','bairro'=>'Praia do Sonho ']);
        Bairro::insert(['id'=>'1212','bairro'=>'Araucária']);
        Bairro::insert(['id'=>'1213','bairro'=>'Área Industrial']);
        Bairro::insert(['id'=>'1214','bairro'=>'Bates']);
        Bairro::insert(['id'=>'1215','bairro'=>'Beatriz']);
        Bairro::insert(['id'=>'1216','bairro'=>'Bela Vista']);
        Bairro::insert(['id'=>'1217','bairro'=>'Bom Jesus']);
        Bairro::insert(['id'=>'1218','bairro'=>'Boqueirão']);
        Bairro::insert(['id'=>'1219','bairro'=>'Brusque']);
        Bairro::insert(['id'=>'1220','bairro'=>'Caça e Tiro']);
        Bairro::insert(['id'=>'1221','bairro'=>'Caravágio']);
        Bairro::insert(['id'=>'1222','bairro'=>'Caroba']);
        Bairro::insert(['id'=>'1223','bairro'=>'CDL']);
        Bairro::insert(['id'=>'1224','bairro'=>'Centenário']);
        Bairro::insert(['id'=>'1225','bairro'=>'Centro']);
        Bairro::insert(['id'=>'1226','bairro'=>'Cidade Alta']);
        Bairro::insert(['id'=>'1227','bairro'=>'Chapada']);
        Bairro::insert(['id'=>'1228','bairro'=>'Conta Dinheiro']);
        Bairro::insert(['id'=>'1229','bairro'=>'Copacabana']);
        Bairro::insert(['id'=>'1230','bairro'=>'Coral']);
        Bairro::insert(['id'=>'1231','bairro'=>'Cruz de Malta']);
        Bairro::insert(['id'=>'1232','bairro'=>'Dom Daniel']);
        Bairro::insert(['id'=>'1233','bairro'=>'Ferrovia']);
        Bairro::insert(['id'=>'1234','bairro'=>'Frei Rogério']);
        Bairro::insert(['id'=>'1235','bairro'=>'Gethal']);
        Bairro::insert(['id'=>'1236','bairro'=>'Gralha Azul']);
        Bairro::insert(['id'=>'1237','bairro'=>'Guadalupe']);
        Bairro::insert(['id'=>'1238','bairro'=>'Guadalajara']);
        Bairro::insert(['id'=>'1239','bairro'=>'Guarujá']);
        Bairro::insert(['id'=>'1240','bairro'=>'Habitação']);
        Bairro::insert(['id'=>'1241','bairro'=>'Ipiranga']);
        Bairro::insert(['id'=>'1242','bairro'=>'Jardim Celina']);
        Bairro::insert(['id'=>'1243','bairro'=>'Jardim das Camélias']);
        Bairro::insert(['id'=>'1244','bairro'=>'Jardim Panorâmico']);
        Bairro::insert(['id'=>'1245','bairro'=>'Maria Luiza']);
        Bairro::insert(['id'=>'1246','bairro'=>'Morro do Posto']);
        Bairro::insert(['id'=>'1247','bairro'=>'Morro Grande']);
        Bairro::insert(['id'=>'1248','bairro'=>'Nossa Senhora Aparecida']);
        Bairro::insert(['id'=>'1249','bairro'=>'Passo Fundo']);
        Bairro::insert(['id'=>'1250','bairro'=>'Penha']);
        Bairro::insert(['id'=>'1251','bairro'=>'Petrópolis']);
        Bairro::insert(['id'=>'1252','bairro'=>'Pisani']);
        Bairro::insert(['id'=>'1253','bairro'=>'Ponte Grande ']);
        Bairro::insert(['id'=>'1254','bairro'=>'Popular']);
        Bairro::insert(['id'=>'1255','bairro'=>'Pró-Morar']);
        Bairro::insert(['id'=>'1256','bairro'=>'Restinga Seca']);
        Bairro::insert(['id'=>'1257','bairro'=>'Sagrado Coração de Jesus']);
        Bairro::insert(['id'=>'1258','bairro'=>'Santa Catarina']);
        Bairro::insert(['id'=>'1259','bairro'=>'Santa Cândida']);
        Bairro::insert(['id'=>'1260','bairro'=>'Santa Clara']);
        Bairro::insert(['id'=>'1261','bairro'=>'Santa Helena']);
        Bairro::insert(['id'=>'1262','bairro'=>'Santa Maria']);
        Bairro::insert(['id'=>'1263','bairro'=>'Santa Mônica']);
        Bairro::insert(['id'=>'1264','bairro'=>'Santa Rita']);
        Bairro::insert(['id'=>'1265','bairro'=>'Santo Antônio']);
        Bairro::insert(['id'=>'1266','bairro'=>'São Cristóvão']);
        Bairro::insert(['id'=>'1267','bairro'=>'São Francisco']);
        Bairro::insert(['id'=>'1268','bairro'=>'São Luiz']);
        Bairro::insert(['id'=>'1269','bairro'=>'São Miguel']);
        Bairro::insert(['id'=>'1270','bairro'=>'São Paulo']);
        Bairro::insert(['id'=>'1271','bairro'=>'São Pedro']);
        Bairro::insert(['id'=>'1272','bairro'=>'São Sebastião']);
        Bairro::insert(['id'=>'1273','bairro'=>'Triângulo']);
        Bairro::insert(['id'=>'1274','bairro'=>'Tributo']);
        Bairro::insert(['id'=>'1275','bairro'=>'Universitário']);
        Bairro::insert(['id'=>'1276','bairro'=>'Várzea']);
        Bairro::insert(['id'=>'1277','bairro'=>'Vila Comboni']);
        Bairro::insert(['id'=>'1278','bairro'=>'Vila Maria']);
        Bairro::insert(['id'=>'1279','bairro'=>'Vila Mariza']);
        Bairro::insert(['id'=>'1280','bairro'=>'Vila Nova']);
        Bairro::insert(['id'=>'1281','bairro'=>'Vista Alegre']);
        Bairro::insert(['id'=>'1282','bairro'=>'Ariribá']);
        Bairro::insert(['id'=>'1283','bairro'=>'Centro']);
        Bairro::insert(['id'=>'1284','bairro'=>'Da Barra']);
        Bairro::insert(['id'=>'1285','bairro'=>'Das Nações']);
        Bairro::insert(['id'=>'1286','bairro'=>'Dos Estados']);
        Bairro::insert(['id'=>'1287','bairro'=>'Dos Municípios']);
        Bairro::insert(['id'=>'1288','bairro'=>'Dos Pioneiros']);
        Bairro::insert(['id'=>'1289','bairro'=>'Jardim Iate Clube']);
        Bairro::insert(['id'=>'1290','bairro'=>'Nova Esperança']);
        Bairro::insert(['id'=>'1291','bairro'=>'Praia dos Amores']);
        Bairro::insert(['id'=>'1292','bairro'=>'Região das Praias']);
        Bairro::insert(['id'=>'1293','bairro'=>'São Judas Tadeu']);
        Bairro::insert(['id'=>'1294','bairro'=>'Várzea do Ranchinho']);
        Bairro::insert(['id'=>'1295','bairro'=>'Vila Real']);
        Bairro::insert(['id'=>'1296','bairro'=>'Águas Claras']);
        Bairro::insert(['id'=>'1297','bairro'=>'Azambuja']);
        Bairro::insert(['id'=>'1298','bairro'=>'Bateas']);
        Bairro::insert(['id'=>'1299','bairro'=>'Cedrinho']);
        Bairro::insert(['id'=>'1300','bairro'=>'Cedro Alto']);
        Bairro::insert(['id'=>'1301','bairro'=>'Cedro Grande']);
        Bairro::insert(['id'=>'1302','bairro'=>'Centro I']);
        Bairro::insert(['id'=>'1303','bairro'=>'Centro II']);
        Bairro::insert(['id'=>'1304','bairro'=>'Cerâmica Reis']);
        Bairro::insert(['id'=>'1305','bairro'=>'Cristalina']);
        Bairro::insert(['id'=>'1306','bairro'=>'Dom Joaquim']);
        Bairro::insert(['id'=>'1307','bairro'=>'Maluche']);
        Bairro::insert(['id'=>'1308','bairro'=>'Limeira']);
        Bairro::insert(['id'=>'1309','bairro'=>'Limeira Baixa']);
        Bairro::insert(['id'=>'1310','bairro'=>'Limoeiro']);
        Bairro::insert(['id'=>'1311','bairro'=>'Nova Brasília']);
        Bairro::insert(['id'=>'1312','bairro'=>'Nova Itália']);
        Bairro::insert(['id'=>'1313','bairro'=>'Poço Fundo']);
        Bairro::insert(['id'=>'1314','bairro'=>'Ponta Russa']);
        Bairro::insert(['id'=>'1315','bairro'=>'Paquetá']);
        Bairro::insert(['id'=>'1316','bairro'=>'Primeiro de Maio']);
        Bairro::insert(['id'=>'1317','bairro'=>'Ribeirão do Mafra']);
        Bairro::insert(['id'=>'1318','bairro'=>'Rio Branco']);
        Bairro::insert(['id'=>'1319','bairro'=>'Santa Luzia']);
        Bairro::insert(['id'=>'1320','bairro'=>'São Pedro']);
        Bairro::insert(['id'=>'1321','bairro'=>'Souza Cruz']);
        Bairro::insert(['id'=>'1322','bairro'=>'Steffen']);
        Bairro::insert(['id'=>'1323','bairro'=>'Tomaz Coelho']);
        Bairro::insert(['id'=>'1324','bairro'=>'Zantão']);
        Bairro::insert(['id'=>'1325','bairro'=>'São Bernardo']);
        Bairro::insert(['id'=>'1326','bairro'=>'São João']);
        Bairro::insert(['id'=>'1327','bairro'=>'Humaitá de Cima']);
        Bairro::insert(['id'=>'1328','bairro'=>'Humaitá Centro']);
        Bairro::insert(['id'=>'1329','bairro'=>'Vila Esperança']);
        Bairro::insert(['id'=>'1330','bairro'=>'Morrotes']);
        Bairro::insert(['id'=>'1331','bairro'=>'Dehon']);
        Bairro::insert(['id'=>'1332','bairro'=>'Revoredo']);
        Bairro::insert(['id'=>'1333','bairro'=>'Cruzeiro']);
        Bairro::insert(['id'=>'1334','bairro'=>'Fábio Silva']);
        Bairro::insert(['id'=>'1335','bairro'=>'Monte Castelo']);
        Bairro::insert(['id'=>'1336','bairro'=>'Oficinas']);
        Bairro::insert(['id'=>'1337','bairro'=>'Centro']);
        Bairro::insert(['id'=>'1338','bairro'=>'Santo Antônio de Pádua']);
        Bairro::insert(['id'=>'1339','bairro'=>'Vila Moema']);
        Bairro::insert(['id'=>'1340','bairro'=>'Recife']);
        Bairro::insert(['id'=>'1341','bairro'=>'Passagem']);
        Bairro::insert(['id'=>'1342','bairro'=>'Passo do gado']);
        Bairro::insert(['id'=>'1343','bairro'=>'Santa Luzia']);
        Bairro::insert(['id'=>'1344','bairro'=>'Praia Redonda']);
        Bairro::insert(['id'=>'1345','bairro'=>'São Clemente']);
        Bairro::insert(['id'=>'1346','bairro'=>'Campestre']);
        Bairro::insert(['id'=>'1347','bairro'=>'São Cristóvão']);
        Bairro::insert(['id'=>'2','bairro'=>'Aberta dos Morros']);
        Bairro::insert(['id'=>'3','bairro'=>'Agronomia']);
        Bairro::insert(['id'=>'4','bairro'=>'Anchieta']);
        Bairro::insert(['id'=>'5','bairro'=>'Arquipélago']);
        Bairro::insert(['id'=>'6','bairro'=>'Auxiliadora']);
        Bairro::insert(['id'=>'7','bairro'=>'Azenha']);
        Bairro::insert(['id'=>'8','bairro'=>'Bela Vista']);
        Bairro::insert(['id'=>'9','bairro'=>'Belém Novo']);
        Bairro::insert(['id'=>'10','bairro'=>'Belém Velho']);
        Bairro::insert(['id'=>'11','bairro'=>'Boa Vista']);
        Bairro::insert(['id'=>'12','bairro'=>'Bom Fim']);
        Bairro::insert(['id'=>'13','bairro'=>'Bom Jesus']);
        Bairro::insert(['id'=>'14','bairro'=>'Camaquã']);
        Bairro::insert(['id'=>'15','bairro'=>'Cascata']);
        Bairro::insert(['id'=>'16','bairro'=>'Cavalhada']);
        Bairro::insert(['id'=>'17','bairro'=>'Centro Histórico']);
        Bairro::insert(['id'=>'18','bairro'=>'Chácara das Pedras']);
        Bairro::insert(['id'=>'19','bairro'=>'Chapéu do Sol']);
        Bairro::insert(['id'=>'20','bairro'=>'Cidade Baixa']);
        Bairro::insert(['id'=>'21','bairro'=>'Coronel Aparício Borges']);
        Bairro::insert(['id'=>'22','bairro'=>'Cristal']);
        Bairro::insert(['id'=>'23','bairro'=>'Cristo Redentor']);
        Bairro::insert(['id'=>'24','bairro'=>'Distrito Industrial']);
        Bairro::insert(['id'=>'25','bairro'=>'Espírito Santo']);
        Bairro::insert(['id'=>'26','bairro'=>'Farrapos']);
        Bairro::insert(['id'=>'27','bairro'=>'Farroupilha']);
        Bairro::insert(['id'=>'28','bairro'=>'Floresta']);
        Bairro::insert(['id'=>'29','bairro'=>'Glória']);
        Bairro::insert(['id'=>'30','bairro'=>'Guarujá']);
        Bairro::insert(['id'=>'31','bairro'=>'Higienópolis']);
        Bairro::insert(['id'=>'32','bairro'=>'Hípica']);
        Bairro::insert(['id'=>'33','bairro'=>'Humaitá']);
        Bairro::insert(['id'=>'34','bairro'=>'Independência']);
        Bairro::insert(['id'=>'35','bairro'=>'Ipanema']);
        Bairro::insert(['id'=>'36','bairro'=>'Jardim Botânico']);
        Bairro::insert(['id'=>'37','bairro'=>'Jardim Carvalho']);
        Bairro::insert(['id'=>'38','bairro'=>'Jardim do Salso']);
        Bairro::insert(['id'=>'39','bairro'=>'Jardim Floresta']);
        Bairro::insert(['id'=>'40','bairro'=>'Jardim Itu Sabará']);
        Bairro::insert(['id'=>'41','bairro'=>'Jardim Lindoia']);
        Bairro::insert(['id'=>'42','bairro'=>'Jardim São Pedro']);
        Bairro::insert(['id'=>'43','bairro'=>'Lageado']);
        Bairro::insert(['id'=>'44','bairro'=>'Lami']);
        Bairro::insert(['id'=>'45','bairro'=>'Lomba do Pinheiro']);
        Bairro::insert(['id'=>'46','bairro'=>'Lomba Pinheiro']);
        Bairro::insert(['id'=>'47','bairro'=>'Marcílio Dias']);
        Bairro::insert(['id'=>'48','bairro'=>'Mário Quintana']);
        Bairro::insert(['id'=>'49','bairro'=>'Medianeira']);
        Bairro::insert(['id'=>'50','bairro'=>'Menino Deus']);
        Bairro::insert(['id'=>'51','bairro'=>'Moinhos de Vento']);
        Bairro::insert(['id'=>'52','bairro'=>'Mont Serrat']);
        Bairro::insert(['id'=>'53','bairro'=>'Morro Santana']);
        Bairro::insert(['id'=>'54','bairro'=>'Navegantes']);
        Bairro::insert(['id'=>'55','bairro'=>'Nonoai']);
        Bairro::insert(['id'=>'56','bairro'=>'Partenon']);
        Bairro::insert(['id'=>'57','bairro'=>'Passo da Areia']);
        Bairro::insert(['id'=>'58','bairro'=>'Passo das Pedras']);
        Bairro::insert(['id'=>'59','bairro'=>'Passo Pedras']);
        Bairro::insert(['id'=>'60','bairro'=>'Pedra Redonda']);
        Bairro::insert(['id'=>'61','bairro'=>'Petrópolis']);
        Bairro::insert(['id'=>'62','bairro'=>'Ponta Grossa']);
        Bairro::insert(['id'=>'63','bairro'=>'Praia de Belas']);
        Bairro::insert(['id'=>'64','bairro'=>'Protásio Alves']);
        Bairro::insert(['id'=>'65','bairro'=>'Restinga']);
        Bairro::insert(['id'=>'66','bairro'=>'Rio Branco']);
        Bairro::insert(['id'=>'67','bairro'=>'Rubem Berta']);
        Bairro::insert(['id'=>'68','bairro'=>'Santa Cecília']);
        Bairro::insert(['id'=>'69','bairro'=>'Santa Maria Goretti']);
        Bairro::insert(['id'=>'70','bairro'=>'Santa Tereza']);
        Bairro::insert(['id'=>'71','bairro'=>'Santana']);
        Bairro::insert(['id'=>'72','bairro'=>'Santo Antônio']);
        Bairro::insert(['id'=>'73','bairro'=>'São Geraldo']);
        Bairro::insert(['id'=>'74','bairro'=>'São João']);
        Bairro::insert(['id'=>'75','bairro'=>'São José']);
        Bairro::insert(['id'=>'76','bairro'=>'São Sebastião']);
        Bairro::insert(['id'=>'77','bairro'=>'Sarandi']);
        Bairro::insert(['id'=>'78','bairro'=>'Serraria']);
        Bairro::insert(['id'=>'79','bairro'=>'Teresópolis']);
        Bairro::insert(['id'=>'80','bairro'=>'Três Figueiras']);
        Bairro::insert(['id'=>'81','bairro'=>'Tristeza']);
        Bairro::insert(['id'=>'82','bairro'=>'Vila Assunção']);
        Bairro::insert(['id'=>'83','bairro'=>'Vila Conceição']);
        Bairro::insert(['id'=>'84','bairro'=>'Vila Ipiranga']);
        Bairro::insert(['id'=>'85','bairro'=>'Vila Jardim']);
        Bairro::insert(['id'=>'86','bairro'=>'Vila João Pessoa']);
        Bairro::insert(['id'=>'87','bairro'=>'Vila Nova']);
        Bairro::insert(['id'=>'1348','bairro'=>'Abranches']);
        Bairro::insert(['id'=>'1349','bairro'=>'Água Verde']);
        Bairro::insert(['id'=>'1350','bairro'=>'Ahú']);
        Bairro::insert(['id'=>'1351','bairro'=>'Alto Boqueirão']);
        Bairro::insert(['id'=>'1352','bairro'=>'Alto da Glória']);
        Bairro::insert(['id'=>'1353','bairro'=>'Alto da XV']);
        Bairro::insert(['id'=>'1354','bairro'=>'Atuba']);
        Bairro::insert(['id'=>'1355','bairro'=>'Augusta']);
        Bairro::insert(['id'=>'1356','bairro'=>'Bacacheri']);
        Bairro::insert(['id'=>'1357','bairro'=>'Bairro Alto']);
        Bairro::insert(['id'=>'1358','bairro'=>'Barreirinha']);
        Bairro::insert(['id'=>'1359','bairro'=>'Batel']);
        Bairro::insert(['id'=>'1360','bairro'=>'Bigorrilho']);
        Bairro::insert(['id'=>'1361','bairro'=>'Boa Vista']);
        Bairro::insert(['id'=>'1362','bairro'=>'Bom Retiro']);
        Bairro::insert(['id'=>'1363','bairro'=>'Boqueirão']);
        Bairro::insert(['id'=>'1364','bairro'=>'Butiatuvinha']);
        Bairro::insert(['id'=>'1365','bairro'=>'Cabral']);
        Bairro::insert(['id'=>'1366','bairro'=>'Cachoeira']);
        Bairro::insert(['id'=>'1367','bairro'=>'Cajuru']);
        Bairro::insert(['id'=>'1368','bairro'=>'Campina do Siqueira']);
        Bairro::insert(['id'=>'1369','bairro'=>'Campo Comprido']);
        Bairro::insert(['id'=>'1370','bairro'=>'Campo de Santana']);
        Bairro::insert(['id'=>'1371','bairro'=>'Capão da Imbuia']);
        Bairro::insert(['id'=>'1372','bairro'=>'Capão Raso']);
        Bairro::insert(['id'=>'1373','bairro'=>'Cascatinha']);
        Bairro::insert(['id'=>'1374','bairro'=>'Centro']);
        Bairro::insert(['id'=>'1375','bairro'=>'Centro Histórico']);
        Bairro::insert(['id'=>'1376','bairro'=>'Caximba']);
        Bairro::insert(['id'=>'1377','bairro'=>'Centro Cívico']);
        Bairro::insert(['id'=>'1378','bairro'=>'Cidade Industrial']);
        Bairro::insert(['id'=>'1379','bairro'=>'Cristo Rei']);
        Bairro::insert(['id'=>'1380','bairro'=>'Fanny']);
        Bairro::insert(['id'=>'1381','bairro'=>'Fazendinha']);
        Bairro::insert(['id'=>'1382','bairro'=>'Ganchinho']);
        Bairro::insert(['id'=>'1383','bairro'=>'Guabirotuba']);
        Bairro::insert(['id'=>'1384','bairro'=>'Guaíra']);
        Bairro::insert(['id'=>'1385','bairro'=>'Hauer']);
        Bairro::insert(['id'=>'1386','bairro'=>'Hugo Lange']);
        Bairro::insert(['id'=>'1387','bairro'=>'Jardim Botânico']);
        Bairro::insert(['id'=>'1388','bairro'=>'Jardim Social']);
        Bairro::insert(['id'=>'1389','bairro'=>'Jardim das Américas']);
        Bairro::insert(['id'=>'1390','bairro'=>'Juvevê']);
        Bairro::insert(['id'=>'1391','bairro'=>'Lamenha Pequena']);
        Bairro::insert(['id'=>'1392','bairro'=>'Lindoia']);
        Bairro::insert(['id'=>'1393','bairro'=>'Mercês']);
        Bairro::insert(['id'=>'1394','bairro'=>'Mossunguê ']);
        Bairro::insert(['id'=>'1395','bairro'=>'Novo Mundo']);
        Bairro::insert(['id'=>'1396','bairro'=>'Orleans']);
        Bairro::insert(['id'=>'1397','bairro'=>'Parolin']);
        Bairro::insert(['id'=>'1398','bairro'=>'Pilarzinho']);
        Bairro::insert(['id'=>'1399','bairro'=>'Pinheirinho']);
        Bairro::insert(['id'=>'1400','bairro'=>'Portão']);
        Bairro::insert(['id'=>'1401','bairro'=>'Prado Velho']);
        Bairro::insert(['id'=>'1402','bairro'=>'Rebouças']);
        Bairro::insert(['id'=>'1403','bairro'=>'Riviera']);
        Bairro::insert(['id'=>'1404','bairro'=>'Santa Cândida']);
        Bairro::insert(['id'=>'1405','bairro'=>'Santa Felicidade']);
        Bairro::insert(['id'=>'1406','bairro'=>'Santa Quitéria']);
        Bairro::insert(['id'=>'1407','bairro'=>'Santo Inácio']);
        Bairro::insert(['id'=>'1408','bairro'=>'São Braz']);
        Bairro::insert(['id'=>'1409','bairro'=>'São Francisco']);
        Bairro::insert(['id'=>'1410','bairro'=>'São João']);
        Bairro::insert(['id'=>'1411','bairro'=>'São Lourenço']);
        Bairro::insert(['id'=>'1412','bairro'=>'São Miguel']);
        Bairro::insert(['id'=>'1413','bairro'=>'Seminário']);
        Bairro::insert(['id'=>'1414','bairro'=>'Sítio Cercado']);
        Bairro::insert(['id'=>'1415','bairro'=>'Taboão']);
        Bairro::insert(['id'=>'1416','bairro'=>'Tarumã']);
        Bairro::insert(['id'=>'1417','bairro'=>'Tatuquara']);
        Bairro::insert(['id'=>'1418','bairro'=>'Tingui']);
        Bairro::insert(['id'=>'1419','bairro'=>'Uberaba']);
        Bairro::insert(['id'=>'1420','bairro'=>'Umbará']);
        Bairro::insert(['id'=>'1421','bairro'=>'Vila Izabel']);
        Bairro::insert(['id'=>'1422','bairro'=>'Vista Alegre']);
        Bairro::insert(['id'=>'1423','bairro'=>'Xaxim']);
        
    
    }
}
