<?php

namespace Database\Seeders;

use App\Models\Cidade;
use Illuminate\Database\Seeder;

class CidadeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Cidade::insert(['id'=>'492','cidade'=>'Angelina']);
        Cidade::insert(['id'=>'493','cidade'=>'Canelinha']);
        Cidade::insert(['id'=>'494','cidade'=>'Leoberto Leal']);
        Cidade::insert(['id'=>'495','cidade'=>'Major Gercino']);
        Cidade::insert(['id'=>'496','cidade'=>'Nova Trento']);
        Cidade::insert(['id'=>'497','cidade'=>'São João Batista']);
        Cidade::insert(['id'=>'498','cidade'=>'Tijucas']);
        Cidade::insert(['id'=>'499','cidade'=>'Antônio Carlos']);
        Cidade::insert(['id'=>'500','cidade'=>'Biguaçu']);
        Cidade::insert(['id'=>'501','cidade'=>'Florianópolis']);
        Cidade::insert(['id'=>'502','cidade'=>'Governador Celso Ramos']);
        Cidade::insert(['id'=>'503','cidade'=>'Palhoça']);
        Cidade::insert(['id'=>'504','cidade'=>'Paulo Lopes']);
        Cidade::insert(['id'=>'505','cidade'=>'Santo Amaro da Imperatriz']);
        Cidade::insert(['id'=>'506','cidade'=>'São José']);
        Cidade::insert(['id'=>'507','cidade'=>'São Pedro de Alcântara']);
        Cidade::insert(['id'=>'508','cidade'=>'Águas Mornas']);
        Cidade::insert(['id'=>'509','cidade'=>'Alfredo Wagner']);
        Cidade::insert(['id'=>'510','cidade'=>'Anitápolis']);
        Cidade::insert(['id'=>'511','cidade'=>'Rancho Queimado']);
        Cidade::insert(['id'=>'512','cidade'=>'São Bonifácio']);
        Cidade::insert(['id'=>'513','cidade'=>'Bela Vista do Toldo']);
        Cidade::insert(['id'=>'514','cidade'=>'Canoinhas']);
        Cidade::insert(['id'=>'515','cidade'=>'Irineópolis']);
        Cidade::insert(['id'=>'516','cidade'=>'Itaiópolis']);
        Cidade::insert(['id'=>'517','cidade'=>'Mafra']);
        Cidade::insert(['id'=>'518','cidade'=>'Major Vieira']);
        Cidade::insert(['id'=>'519','cidade'=>'Monte Castelo']);
        Cidade::insert(['id'=>'520','cidade'=>'Papanduva']);
        Cidade::insert(['id'=>'521','cidade'=>'Porto União']);
        Cidade::insert(['id'=>'522','cidade'=>'Santa Terezinha']);
        Cidade::insert(['id'=>'523','cidade'=>'Timbó Grande']);
        Cidade::insert(['id'=>'524','cidade'=>'Três Barras']);
        Cidade::insert(['id'=>'525','cidade'=>'Campo Alegre']);
        Cidade::insert(['id'=>'526','cidade'=>'Rio Negrinho']);
        Cidade::insert(['id'=>'527','cidade'=>'São Bento do Sul']);
        Cidade::insert(['id'=>'528','cidade'=>'Araquari']);
        Cidade::insert(['id'=>'529','cidade'=>'Balneário Barra do Sul']);
        Cidade::insert(['id'=>'530','cidade'=>'Corupá']);
        Cidade::insert(['id'=>'531','cidade'=>'Garuva']);
        Cidade::insert(['id'=>'532','cidade'=>'Guaramirim']);
        Cidade::insert(['id'=>'533','cidade'=>'Itapoá']);
        Cidade::insert(['id'=>'534','cidade'=>'Jaraguá do Sul']);
        Cidade::insert(['id'=>'535','cidade'=>'Joinville']);
        Cidade::insert(['id'=>'536','cidade'=>'Massaranduba']);
        Cidade::insert(['id'=>'537','cidade'=>'São Francisco do Sul']);
        Cidade::insert(['id'=>'538','cidade'=>'Schroeder']);
        Cidade::insert(['id'=>'539','cidade'=>'Abdon Batista']);
        Cidade::insert(['id'=>'540','cidade'=>'Anita Garibaldi']);
        Cidade::insert(['id'=>'541','cidade'=>'Bocaina do Sul']);
        Cidade::insert(['id'=>'542','cidade'=>'Bom Jardim da Serra']);
        Cidade::insert(['id'=>'543','cidade'=>'Bom Retiro']);
        Cidade::insert(['id'=>'544','cidade'=>'Brunópolis']);
        Cidade::insert(['id'=>'545','cidade'=>'Campo Belo do Sul']);
        Cidade::insert(['id'=>'546','cidade'=>'Campos Novos']);
        Cidade::insert(['id'=>'547','cidade'=>'Capão Alto']);
        Cidade::insert(['id'=>'548','cidade'=>'Celso Ramos']);
        Cidade::insert(['id'=>'549','cidade'=>'Cerro Negro']);
        Cidade::insert(['id'=>'550','cidade'=>'Correia Pinto']);
        Cidade::insert(['id'=>'551','cidade'=>'Curitibanos']);
        Cidade::insert(['id'=>'552','cidade'=>'Frei Rogério']);
        Cidade::insert(['id'=>'553','cidade'=>'Lages']);
        Cidade::insert(['id'=>'554','cidade'=>'Monte Carlo']);
        Cidade::insert(['id'=>'555','cidade'=>'Otacílio Costa']);
        Cidade::insert(['id'=>'556','cidade'=>'Painel']);
        Cidade::insert(['id'=>'557','cidade'=>'Palmeira']);
        Cidade::insert(['id'=>'558','cidade'=>'Ponte Alta']);
        Cidade::insert(['id'=>'559','cidade'=>'Ponte Alta do Norte']);
        Cidade::insert(['id'=>'560','cidade'=>'Rio Rufino']);
        Cidade::insert(['id'=>'561','cidade'=>'Santa Cecília']);
        Cidade::insert(['id'=>'562','cidade'=>'São Cristóvão do Sul']);
        Cidade::insert(['id'=>'563','cidade'=>'São Joaquim']);
        Cidade::insert(['id'=>'564','cidade'=>'São José do Cerrito']);
        Cidade::insert(['id'=>'565','cidade'=>'Urubici']);
        Cidade::insert(['id'=>'566','cidade'=>'Urupema']);
        Cidade::insert(['id'=>'567','cidade'=>'Vargem']);
        Cidade::insert(['id'=>'568','cidade'=>'Zortéa']);
        Cidade::insert(['id'=>'569','cidade'=>'Agrolândia']);
        Cidade::insert(['id'=>'570','cidade'=>'Agronômica']);
        Cidade::insert(['id'=>'571','cidade'=>'Apiúna']);
        Cidade::insert(['id'=>'572','cidade'=>'Ascurra']);
        Cidade::insert(['id'=>'573','cidade'=>'Atalanta']);
        Cidade::insert(['id'=>'574','cidade'=>'Aurora']);
        Cidade::insert(['id'=>'575','cidade'=>'Balneário Camboriú']);
        Cidade::insert(['id'=>'576','cidade'=>'Balneário Piçarras']);
        Cidade::insert(['id'=>'577','cidade'=>'Barra Velha']);
        Cidade::insert(['id'=>'578','cidade'=>'Benedito Novo']);
        Cidade::insert(['id'=>'579','cidade'=>'Blumenau']);
        Cidade::insert(['id'=>'580','cidade'=>'Bombinhas']);
        Cidade::insert(['id'=>'581','cidade'=>'Botuverá']);
        Cidade::insert(['id'=>'582','cidade'=>'Braço do Trombudo']);
        Cidade::insert(['id'=>'583','cidade'=>'Brusque']);
        Cidade::insert(['id'=>'584','cidade'=>'Camboriú']);
        Cidade::insert(['id'=>'585','cidade'=>'Chapadão do Lageado']);
        Cidade::insert(['id'=>'586','cidade'=>'Dona Emma']);
        Cidade::insert(['id'=>'587','cidade'=>'Doutor Pedrinho']);
        Cidade::insert(['id'=>'588','cidade'=>'Gaspar']);
        Cidade::insert(['id'=>'589','cidade'=>'Guabiruba']);
        Cidade::insert(['id'=>'590','cidade'=>'Ibirama']);
        Cidade::insert(['id'=>'591','cidade'=>'Ilhota']);
        Cidade::insert(['id'=>'592','cidade'=>'Imbuia']);
        Cidade::insert(['id'=>'593','cidade'=>'Indaial']);
        Cidade::insert(['id'=>'594','cidade'=>'Itajaí']);
        Cidade::insert(['id'=>'595','cidade'=>'Itapema']);
        Cidade::insert(['id'=>'596','cidade'=>'Ituporanga']);
        Cidade::insert(['id'=>'597','cidade'=>'José Boiteux']);
        Cidade::insert(['id'=>'598','cidade'=>'Laurentino']);
        Cidade::insert(['id'=>'599','cidade'=>'Lontras']);
        Cidade::insert(['id'=>'600','cidade'=>'Luiz Alves']);
        Cidade::insert(['id'=>'601','cidade'=>'Mirim Doce']);
        Cidade::insert(['id'=>'602','cidade'=>'Navegantes']);
        Cidade::insert(['id'=>'603','cidade'=>'Penha']);
        Cidade::insert(['id'=>'604','cidade'=>'Petrolândia']);
        Cidade::insert(['id'=>'605','cidade'=>'Pomerode']);
        Cidade::insert(['id'=>'606','cidade'=>'Porto Belo']);
        Cidade::insert(['id'=>'607','cidade'=>'Pouso Redondo']);
        Cidade::insert(['id'=>'608','cidade'=>'Presidente Getúlio']);
        Cidade::insert(['id'=>'609','cidade'=>'Presidente Nereu']);
        Cidade::insert(['id'=>'610','cidade'=>'Rio do Campo']);
        Cidade::insert(['id'=>'611','cidade'=>'Rio do Oeste']);
        Cidade::insert(['id'=>'612','cidade'=>'Rio do Sul']);
        Cidade::insert(['id'=>'613','cidade'=>'Rio dos Cedros']);
        Cidade::insert(['id'=>'614','cidade'=>'Rodeio']);
        Cidade::insert(['id'=>'615','cidade'=>'Salete']);
        Cidade::insert(['id'=>'616','cidade'=>'São João do Itaperiú']);
        Cidade::insert(['id'=>'617','cidade'=>'Taió']);
        Cidade::insert(['id'=>'618','cidade'=>'Timbó']);
        Cidade::insert(['id'=>'619','cidade'=>'Trombudo Central']);
        Cidade::insert(['id'=>'620','cidade'=>'Vidal Ramos']);
        Cidade::insert(['id'=>'621','cidade'=>'Vitor Meireles']);
        Cidade::insert(['id'=>'622','cidade'=>'Witmarsum']);
        Cidade::insert(['id'=>'623','cidade'=>'Abelardo Luz']);
        Cidade::insert(['id'=>'624','cidade'=>'Água Doce']);
        Cidade::insert(['id'=>'625','cidade'=>'Águas de Chapecó']);
        Cidade::insert(['id'=>'626','cidade'=>'Águas Frias']);
        Cidade::insert(['id'=>'627','cidade'=>'Alto Bela Vista']);
        Cidade::insert(['id'=>'628','cidade'=>'Anchieta']);
        Cidade::insert(['id'=>'629','cidade'=>'Arabutã']);
        Cidade::insert(['id'=>'630','cidade'=>'Arroio Trinta']);
        Cidade::insert(['id'=>'631','cidade'=>'Arvoredo']);
        Cidade::insert(['id'=>'632','cidade'=>'Bandeirante']);
        Cidade::insert(['id'=>'633','cidade'=>'Barra Bonita']);
        Cidade::insert(['id'=>'634','cidade'=>'Belmonte']);
        Cidade::insert(['id'=>'635','cidade'=>'Bom Jesus']);
        Cidade::insert(['id'=>'636','cidade'=>'Bom Jesus do Oeste']);
        Cidade::insert(['id'=>'637','cidade'=>'Caçador']);
        Cidade::insert(['id'=>'638','cidade'=>'Caibi']);
        Cidade::insert(['id'=>'639','cidade'=>'Calmon']);
        Cidade::insert(['id'=>'640','cidade'=>'Campo Erê']);
        Cidade::insert(['id'=>'641','cidade'=>'Capinzal']);
        Cidade::insert(['id'=>'642','cidade'=>'Catanduvas']);
        Cidade::insert(['id'=>'643','cidade'=>'Caxambu do Sul']);
        Cidade::insert(['id'=>'644','cidade'=>'Chapecó']);
        Cidade::insert(['id'=>'645','cidade'=>'Concórdia']);
        Cidade::insert(['id'=>'646','cidade'=>'Cordilheira Alta']);
        Cidade::insert(['id'=>'647','cidade'=>'Coronel Freitas']);
        Cidade::insert(['id'=>'648','cidade'=>'Coronel Martins']);
        Cidade::insert(['id'=>'649','cidade'=>'Cunha Porã']);
        Cidade::insert(['id'=>'650','cidade'=>'Cunhataí']);
        Cidade::insert(['id'=>'651','cidade'=>'Descanso']);
        Cidade::insert(['id'=>'652','cidade'=>'Dionísio Cerqueira']);
        Cidade::insert(['id'=>'653','cidade'=>'Entre Rios']);
        Cidade::insert(['id'=>'654','cidade'=>'Erval Velho']);
        Cidade::insert(['id'=>'655','cidade'=>'Faxinal dos Guedes']);
        Cidade::insert(['id'=>'656','cidade'=>'Flor do Sertão']);
        Cidade::insert(['id'=>'657','cidade'=>'Formosa do Sul']);
        Cidade::insert(['id'=>'658','cidade'=>'Fraiburgo']);
        Cidade::insert(['id'=>'659','cidade'=>'Galvão']);
        Cidade::insert(['id'=>'660','cidade'=>'Guaraciaba']);
        Cidade::insert(['id'=>'661','cidade'=>'Guarujá do Sul']);
        Cidade::insert(['id'=>'662','cidade'=>'Guatambu']);
        Cidade::insert(['id'=>'663','cidade'=>'Herval dOeste']);
        Cidade::insert(['id'=>'664','cidade'=>'Ibiam']);
        Cidade::insert(['id'=>'665','cidade'=>'Ibicaré']);
        Cidade::insert(['id'=>'666','cidade'=>'Iomerê']);
        Cidade::insert(['id'=>'667','cidade'=>'Ipira']);
        Cidade::insert(['id'=>'668','cidade'=>'Iporã do Oeste']);
        Cidade::insert(['id'=>'669','cidade'=>'Ipuaçu']);
        Cidade::insert(['id'=>'670','cidade'=>'Ipumirim']);
        Cidade::insert(['id'=>'671','cidade'=>'Iraceminha']);
        Cidade::insert(['id'=>'672','cidade'=>'Irani']);
        Cidade::insert(['id'=>'673','cidade'=>'Irati']);
        Cidade::insert(['id'=>'674','cidade'=>'Itá']);
        Cidade::insert(['id'=>'675','cidade'=>'Itapiranga']);
        Cidade::insert(['id'=>'676','cidade'=>'Jaborá']);
        Cidade::insert(['id'=>'677','cidade'=>'Jardinópolis']);
        Cidade::insert(['id'=>'678','cidade'=>'Joaçaba']);
        Cidade::insert(['id'=>'679','cidade'=>'Jupiá']);
        Cidade::insert(['id'=>'680','cidade'=>'Lacerdópolis']);
        Cidade::insert(['id'=>'681','cidade'=>'Lajeado Grande']);
        Cidade::insert(['id'=>'682','cidade'=>'Lebon Régis']);
        Cidade::insert(['id'=>'683','cidade'=>'Lindóia do Sul']);
        Cidade::insert(['id'=>'684','cidade'=>'Luzerna']);
        Cidade::insert(['id'=>'685','cidade'=>'Macieira']);
        Cidade::insert(['id'=>'686','cidade'=>'Maravilha']);
        Cidade::insert(['id'=>'687','cidade'=>'Marema']);
        Cidade::insert(['id'=>'688','cidade'=>'Matos Costa']);
        Cidade::insert(['id'=>'689','cidade'=>'Modelo']);
        Cidade::insert(['id'=>'690','cidade'=>'Mondaí']);
        Cidade::insert(['id'=>'691','cidade'=>'Nova Erechim']);
        Cidade::insert(['id'=>'692','cidade'=>'Nova Itaberaba']);
        Cidade::insert(['id'=>'693','cidade'=>'Novo Horizonte']);
        Cidade::insert(['id'=>'694','cidade'=>'Ouro']);
        Cidade::insert(['id'=>'695','cidade'=>'Ouro Verde']);
        Cidade::insert(['id'=>'696','cidade'=>'Paial']);
        Cidade::insert(['id'=>'697','cidade'=>'Palma Sola']);
        Cidade::insert(['id'=>'698','cidade'=>'Palmitos']);
        Cidade::insert(['id'=>'699','cidade'=>'Paraíso']);
        Cidade::insert(['id'=>'700','cidade'=>'Passos Maia']);
        Cidade::insert(['id'=>'701','cidade'=>'Peritiba']);
        Cidade::insert(['id'=>'702','cidade'=>'Pinhalzinho']);
        Cidade::insert(['id'=>'703','cidade'=>'Pinheiro Preto']);
        Cidade::insert(['id'=>'704','cidade'=>'Piratuba']);
        Cidade::insert(['id'=>'705','cidade'=>'Planalto Alegre']);
        Cidade::insert(['id'=>'706','cidade'=>'Ponte Serrada']);
        Cidade::insert(['id'=>'707','cidade'=>'Presidente Castelo Branco']);
        Cidade::insert(['id'=>'708','cidade'=>'Princesa']);
        Cidade::insert(['id'=>'709','cidade'=>'Quilombo']);
        Cidade::insert(['id'=>'710','cidade'=>'Rio das Antas']);
        Cidade::insert(['id'=>'711','cidade'=>'Riqueza']);
        Cidade::insert(['id'=>'712','cidade'=>'Romelândia']);
        Cidade::insert(['id'=>'713','cidade'=>'Saltinho']);
        Cidade::insert(['id'=>'714','cidade'=>'Salto Veloso']);
        Cidade::insert(['id'=>'715','cidade'=>'Santa Helena']);
        Cidade::insert(['id'=>'716','cidade'=>'Santa Terezinha do Progresso']);
        Cidade::insert(['id'=>'717','cidade'=>'Santiago do Sul']);
        Cidade::insert(['id'=>'718','cidade'=>'São Bernardino']);
        Cidade::insert(['id'=>'719','cidade'=>'São Carlos']);
        Cidade::insert(['id'=>'720','cidade'=>'São Domingos']);
        Cidade::insert(['id'=>'721','cidade'=>'São João do Oeste']);
        Cidade::insert(['id'=>'722','cidade'=>'São José do Cedro']);
        Cidade::insert(['id'=>'723','cidade'=>'São Lourenço do Oeste']);
        Cidade::insert(['id'=>'724','cidade'=>'São Miguel da Boa Vista']);
        Cidade::insert(['id'=>'725','cidade'=>'São Miguel do Oeste']);
        Cidade::insert(['id'=>'726','cidade'=>'Saudades']);
        Cidade::insert(['id'=>'727','cidade'=>'Seara']);
        Cidade::insert(['id'=>'728','cidade'=>'Serra Alta']);
        Cidade::insert(['id'=>'729','cidade'=>'Sul Brasil']);
        Cidade::insert(['id'=>'730','cidade'=>'Tangará']);
        Cidade::insert(['id'=>'731','cidade'=>'Tigrinhos']);
        Cidade::insert(['id'=>'732','cidade'=>'Treze Tílias']);
        Cidade::insert(['id'=>'733','cidade'=>'Tunápolis']);
        Cidade::insert(['id'=>'734','cidade'=>'União do Oeste']);
        Cidade::insert(['id'=>'735','cidade'=>'Vargeão']);
        Cidade::insert(['id'=>'736','cidade'=>'Vargem Bonita']);
        Cidade::insert(['id'=>'737','cidade'=>'Videira']);
        Cidade::insert(['id'=>'738','cidade'=>'Xanxerê']);
        Cidade::insert(['id'=>'739','cidade'=>'Xavantina']);
        Cidade::insert(['id'=>'740','cidade'=>'Xaxim']);
        Cidade::insert(['id'=>'741','cidade'=>'Araranguá']);
        Cidade::insert(['id'=>'742','cidade'=>'Armazém']);
        Cidade::insert(['id'=>'743','cidade'=>'Balneário Arroio do Silva']);
        Cidade::insert(['id'=>'744','cidade'=>'Balneário Gaivota']);
        Cidade::insert(['id'=>'745','cidade'=>'Balneário Rincão']);
        Cidade::insert(['id'=>'746','cidade'=>'Braço do Norte']);
        Cidade::insert(['id'=>'747','cidade'=>'Capivari de Baixo']);
        Cidade::insert(['id'=>'748','cidade'=>'Cocal do Sul']);
        Cidade::insert(['id'=>'749','cidade'=>'Criciúma']);
        Cidade::insert(['id'=>'750','cidade'=>'Ermo']);
        Cidade::insert(['id'=>'751','cidade'=>'Forquilhinha']);
        Cidade::insert(['id'=>'752','cidade'=>'Garopaba']);
        Cidade::insert(['id'=>'753','cidade'=>'Grão Pará']);
        Cidade::insert(['id'=>'754','cidade'=>'Gravatal']);
        Cidade::insert(['id'=>'755','cidade'=>'Içara']);
        Cidade::insert(['id'=>'756','cidade'=>'Imaruí']);
        Cidade::insert(['id'=>'757','cidade'=>'Imbituba']);
        Cidade::insert(['id'=>'758','cidade'=>'Jacinto Machado']);
        Cidade::insert(['id'=>'759','cidade'=>'Jaguaruna']);
        Cidade::insert(['id'=>'760','cidade'=>'Laguna']);
        Cidade::insert(['id'=>'761','cidade'=>'Lauro Müller']);
        Cidade::insert(['id'=>'762','cidade'=>'Maracajá']);
        Cidade::insert(['id'=>'763','cidade'=>'Meleiro']);
        Cidade::insert(['id'=>'764','cidade'=>'Morro da Fumaça']);
        Cidade::insert(['id'=>'765','cidade'=>'Morro Grande']);
        Cidade::insert(['id'=>'766','cidade'=>'Nova Veneza']);
        Cidade::insert(['id'=>'767','cidade'=>'Orleans']);
        Cidade::insert(['id'=>'768','cidade'=>'Passo de Torres']);
        Cidade::insert(['id'=>'769','cidade'=>'Pedras Grandes']);
        Cidade::insert(['id'=>'770','cidade'=>'Pescaria Brava']);
        Cidade::insert(['id'=>'771','cidade'=>'Praia Grande']);
        Cidade::insert(['id'=>'772','cidade'=>'Rio Fortuna']);
        Cidade::insert(['id'=>'773','cidade'=>'Sangão']);
        Cidade::insert(['id'=>'774','cidade'=>'Santa Rosa de Lima']);
        Cidade::insert(['id'=>'775','cidade'=>'Santa Rosa do Sul']);
        Cidade::insert(['id'=>'776','cidade'=>'São João do Sul']);
        Cidade::insert(['id'=>'777','cidade'=>'São Ludgero']);
        Cidade::insert(['id'=>'778','cidade'=>'São Martinho']);
        Cidade::insert(['id'=>'779','cidade'=>'Siderópolis']);
        Cidade::insert(['id'=>'780','cidade'=>'Sombrio']);
        Cidade::insert(['id'=>'781','cidade'=>'Timbé do Sul']);
        Cidade::insert(['id'=>'782','cidade'=>'Treviso']);
        Cidade::insert(['id'=>'783','cidade'=>'Treze de Maio']);
        Cidade::insert(['id'=>'784','cidade'=>'Tubarão']);
        Cidade::insert(['id'=>'785','cidade'=>'Turvo']);
        Cidade::insert(['id'=>'786','cidade'=>'Urussanga']);
        Cidade::insert(['id'=>'406','cidade'=>'Porto Alegre']);
        Cidade::insert(['id'=>'1163','cidade'=>'Curitiba']);
        
    
    }
}
